site_name: WidgetBot Crate

# Repository
repo_name: 'widgetbot-io/crate-docs'
repo_url: 'https://github.com/widgetbot-io/crate-docs'
edit_uri: 'https://github.com/widgetbot-io/crate-docs/edit/master/docs/'

# Meta
site_description: 'Popup Discord widgets for your website.'
site_author: 'WidgetBot'
copyright: 'Copyright &copy; 2018 WidgetBot'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.ico'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'

# Pages
pages:
  - Introduction: 'index.md'
  - Options: 'options/index.md'
  - API: 'api/index.md'
  - Examples: 'examples/index.md'

  # Extensions
markdown_extensions:
  - toc:
      permalink: true
  - meta
  - footnotes
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# Resources
extra_javascript:
  - 'assets/js/crate.js'
extra_css:
  - 'assets/css/main.css'

# Analytics
# google_analytics:
#   - 'UA-85426772-6'
#   - 'auto'

# Footer links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/widgetbot-io'
    - type: 'twitter'
      link: 'https://twitter.com/widgetbot'