site_name: WidgetBot.io

# Repository
repo_name: 'widgetbot-io/embed'
repo_url: 'https://github.com/widgetbot-io/embed'
edit_uri: 'https://github.com/widgetbot-io/documentation/edit/master/docs/'

# Meta
site_description: 'Discord chat widgets for your website.'
site_author: 'WidgetBot'
copyright: 'Copyright &copy; 2018 Sam Denty'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.ico'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'

# Pages
pages:
  - Welcome: 'index.md'
  - crate:
    - Intro: 'crate/index.md'
    - Options: 'crate/options/index.md'
    - API: 'crate/api.md'
    - Examples: 'crate/examples/index.md'
  - html-embed:
    - Intro: 'html-embed/index.md'
    - Attributes: 'html-embed/attributes.md'
    - API: 'html-embed/api.md'
  - react-embed:
    - Intro: 'react-embed/index.md'
    - Props: 'react-embed/props.md'
    - API: 'react-embed/api.md'

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs
  - meta
  - footnotes
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# Resources
extra_javascript:
  - 'assets/js/crate.js'
extra_css:
  - 'assets/css/main.css'
  - 'assets/css/dark.css'

# Analytics
# google_analytics:
#   - 'UA-85426772-6'
#   - 'auto'

# Footer links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/widgetbot-io'
    - type: 'twitter'
      link: 'https://twitter.com/widgetbot'
